export const posts = [
  {
    id: 1,
    src: "/blog/posts/img1.jpg",
    icon: "/blog/posts/user1.jpg",
    title: "As yen tumbles, gadget-loving Japan goes for secondhand iPhones ",
    cat: "Lifestyle",
    view: 4308,
    comment: 3,
    date: "Sat, May 3",
  },
  {
    id: 2,
    src: "/blog/posts/img2.jpg",
    icon: "/blog/posts/user2.jpg",
    title:
      "Intel loses bid to revive antitrust case against patent foe Fortress",
    cat: "Lifestyle",
    view: 9552,
    comment: 3,
    date: "Fri, May 2",
  },
  {
    id: 3,
    src: "/blog/posts/img3.jpg",
    icon: "/blog/posts/user3.jpg",
    title: "COVID outbreak deepens as more lockdowns loom in China",
    cat: "Lifestyle",
    view: 7021,
    comment: 3,
    date: "Thu, May 1",
  },
  {
    id: 4,
    src: "/blog/posts/img4.jpg",
    icon: "/blog/posts/user4.jpg",
    title: "Streaming video way before it was cool, go dark tomorrow",
    cat: "Lifestyle",
    view: 3859,
    comment: 3,
    date: "Thu, May 1",
  },
  {
    id: 5,
    src: "/blog/posts/img5.jpg",
    icon: "/blog/posts/user5.jpg",
    title:
      "Apple is apparently working on a new streamlined accessibility for iOS",
    cat: "Lifestyle",
    view: 4308,
    comment: 3,
    date: "Wed, Apr 30",
  },
  {
    id: 6,
    src: "/blog/posts/img6.jpg",
    icon: "/blog/posts/user6.jpg",
    title: "After Twitter Staff Cuts, Survivors Face Radio Silence",
    cat: "Lifestyle",
    view: 9870,
    comment: 3,
    date: "Mon, Apr 28",
  },
];
